name: Container Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          podman build -t q:latest .

      - name: Verify image exists
        run: |
          podman images | grep q

      - name: Run Container
        run: |
          podman run -d -p 9095:9095 --name q-app q:latest
          sleep 1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run E2E Tests
        run: cargo test --features e2e --test e2e_test
        env:
          SERVER_URL: http://0.0.0.0:9095

      - name: Container Logs on Failure
        if: failure()
        run: podman logs q-app

      - name: Kill runnig container
        if: always()
        run: podman kill q-app
